
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class DopDosGeneration extends javax.swing.JPanel {
    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet rs = null;

    /**
     * Creates new form DopDosGeneration
     */
    public DopDosGeneration() {
        initComponents();
        conn = SlamSqlConnect.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblSubjectid = new javax.swing.JLabel();
        txtSubjecId = new javax.swing.JTextField();
        lblNOfExp = new javax.swing.JLabel();
        txtNOfExp = new javax.swing.JTextField();
        lblDOP = new javax.swing.JLabel();
        jdcDOP = new com.toedter.calendar.JDateChooser();
        lblDOS = new javax.swing.JLabel();
        jdcDOS = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDopDosTableData = new javax.swing.JTable();
        btnGenerate = new javax.swing.JButton();
        subjectidSep = new javax.swing.JSeparator();
        noOfExpSep = new javax.swing.JSeparator();
        cmbGapInDates = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1400, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(28, 40, 15));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 105));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblSubjectid.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblSubjectid.setForeground(new java.awt.Color(110, 160, 58));
        lblSubjectid.setText("Subject ID");

        txtSubjecId.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtSubjecId.setBorder(null);
        txtSubjecId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubjecIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubjecIdFocusLost(evt);
            }
        });
        txtSubjecId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjecIdActionPerformed(evt);
            }
        });

        lblNOfExp.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblNOfExp.setForeground(new java.awt.Color(110, 160, 58));
        lblNOfExp.setText("Number of Experiments");

        txtNOfExp.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtNOfExp.setBorder(null);
        txtNOfExp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNOfExpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNOfExpFocusLost(evt);
            }
        });

        lblDOP.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblDOP.setForeground(new java.awt.Color(110, 160, 58));
        lblDOP.setText("DOP");

        lblDOS.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblDOS.setForeground(new java.awt.Color(110, 160, 58));
        lblDOS.setText("DOS");

        jDopDosTableData.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jDopDosTableData.setForeground(new java.awt.Color(28, 40, 15));
        jDopDosTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DOP", "DOS"
            }
        ));
        jDopDosTableData.setRowHeight(20);
        jDopDosTableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDopDosTableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDopDosTableData);

        btnGenerate.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerate.setFont(new java.awt.Font("Arima Madurai Black", 1, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.setBorder(null);
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        subjectidSep.setBackground(new java.awt.Color(110, 160, 58));

        noOfExpSep.setBackground(new java.awt.Color(110, 160, 58));

        cmbGapInDates.setFont(new java.awt.Font("Arima Madurai Black", 0, 18)); // NOI18N
        cmbGapInDates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cmbGapInDates.setSelectedIndex(-1);
        cmbGapInDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGapInDatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSubjecId)
                        .addComponent(lblNOfExp, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                        .addComponent(txtNOfExp)
                        .addComponent(jdcDOP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdcDOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDOP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubjectid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subjectidSep)
                        .addComponent(noOfExpSep)
                        .addComponent(cmbGapInDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblSubjectid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubjecId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectidSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNOfExp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNOfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(noOfExpSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDOP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbGapInDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1376, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubjecIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjecIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjecIdActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql = "INSERT INTO experiment(experimentno, DOP, DOS, subid)"
                    + "VALUES(?,?,?,?)";
        preparedStatement = conn.prepareStatement(sql);
        nOfExp = Integer.parseInt(txtNOfExp.getText());
        gapInDates = Integer.parseInt((String)cmbGapInDates.getSelectedItem());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = Calendar.getInstance();
        initialDOP = sdf.format(jdcDOP.getDate());
        initialDOS = sdf.format(jdcDOS.getDate());
        c1.setTime(sdf.parse(initialDOP));
        c2.setTime(sdf.parse(initialDOS));
        jDopDosTableData.setValueAt(initialDOP,0,0);
        jDopDosTableData.setValueAt(initialDOS,0,1);
        preparedStatement.setInt(1,1);
        preparedStatement.setString(2, initialDOP);
        preparedStatement.setString(3, initialDOS);
        preparedStatement.setInt(4,Integer.parseInt((txtSubjecId.getText())));
        preparedStatement.execute();
        for(int i = 1,j=2; i<=nOfExp-1; i++,j++){
          preparedStatement.setInt(1,j);
          if(i%2!=0){
          c1.add(Calendar.DATE,gapInDates);
          jDopDosTableData.setValueAt(sdf.format(c1.getTime()),i,0);
          preparedStatement.setString(2, sdf.format(c1.getTime()));
          c2.add(Calendar.DATE,(7-gapInDates));
          jDopDosTableData.setValueAt(sdf.format(c2.getTime()),i,1);
          preparedStatement.setString(3, sdf.format(c2.getTime()));
          }
          else if(i%2==0){
          c1.add(Calendar.DATE,(7-gapInDates));
          jDopDosTableData.setValueAt(sdf.format(c1.getTime()),i,0);
          preparedStatement.setString(2, sdf.format(c1.getTime()));
          c2.add(Calendar.DATE,gapInDates);
          jDopDosTableData.setValueAt(sdf.format(c2.getTime()),i,1);
          preparedStatement.setString(3, sdf.format(c2.getTime()));              
          }
          preparedStatement.executeUpdate();
        }
        
        JOptionPane.showMessageDialog(null, "Dop Dos Generated Successfully!");
        
        }catch(Exception e){
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void jDopDosTableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDopDosTableDataMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jDopDosTableDataMouseClicked

    private void txtSubjecIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubjecIdFocusGained
        // TODO add your handling code here:
        lblSubjectid.setForeground(new Color(28,40,15));
        subjectidSep.setBackground(new Color(28,40,15));
    }//GEN-LAST:event_txtSubjecIdFocusGained

    private void txtSubjecIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubjecIdFocusLost
        // TODO add your handling code here:
        lblSubjectid.setForeground(new Color(110,160,58));
        subjectidSep.setBackground(new Color(110,160,58));
    }//GEN-LAST:event_txtSubjecIdFocusLost

    private void txtNOfExpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNOfExpFocusGained
        // TODO add your handling code here:
        lblNOfExp.setForeground(new Color(28,40,15));
        noOfExpSep.setBackground(new Color(28,40,15));
    }//GEN-LAST:event_txtNOfExpFocusGained

    private void txtNOfExpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNOfExpFocusLost
        // TODO add your handling code here:
        lblNOfExp.setForeground(new Color(110,160,58));
        noOfExpSep.setBackground(new Color(110,160,58));
    }//GEN-LAST:event_txtNOfExpFocusLost

    private void cmbGapInDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGapInDatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGapInDatesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JComboBox<String> cmbGapInDates;
    private javax.swing.JTable jDopDosTableData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcDOP;
    private com.toedter.calendar.JDateChooser jdcDOS;
    private javax.swing.JLabel lblDOP;
    private javax.swing.JLabel lblDOS;
    private javax.swing.JLabel lblNOfExp;
    private javax.swing.JLabel lblSubjectid;
    private javax.swing.JSeparator noOfExpSep;
    private javax.swing.JSeparator subjectidSep;
    private javax.swing.JTextField txtNOfExp;
    private javax.swing.JTextField txtSubjecId;
    // End of variables declaration//GEN-END:variables
    int nOfExp;
    String initialDOP = null;
    String initialDOS = null;
    int gapInDates;
}
