import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class SlamLoginPage extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet rs = null;
    /** 
     * Creates new form SlamLoginPage
     */
    public SlamLoginPage() {
 
        initComponents();
        conn = SlamSqlConnect.connectDb();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblLoginUsername = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        lblCancel = new javax.swing.JLabel();
        loginUsernameSep = new javax.swing.JSeparator();
        loginPasswordSep = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        usernameSep = new javax.swing.JSeparator();
        passwordSep = new javax.swing.JSeparator();
        emailSep = new javax.swing.JSeparator();
        contactNoSep = new javax.swing.JSeparator();
        lblSignup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SlamLoginPage");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 750));

        jPanel4.setBackground(new java.awt.Color(111, 255, 233));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/lock.png"))); // NOI18N

        lblLoginUsername.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblLoginUsername.setForeground(new java.awt.Color(24, 27, 59));
        lblLoginUsername.setText("Username");

        txtLoginUsername.setBackground(new java.awt.Color(111, 255, 233));
        txtLoginUsername.setFont(new java.awt.Font("Arima Madurai Black", 0, 18)); // NOI18N
        txtLoginUsername.setBorder(null);
        txtLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsernameActionPerformed(evt);
            }
        });

        lblLoginPassword.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblLoginPassword.setForeground(new java.awt.Color(24, 27, 59));
        lblLoginPassword.setText("Password");

        txtLoginPassword.setBackground(new java.awt.Color(111, 255, 233));
        txtLoginPassword.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtLoginPassword.setBorder(null);
        txtLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPasswordActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(24, 27, 59));
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/Unlock-icon.png"))); // NOI18N
        lblLogin.setText("Login");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
        });

        lblCancel.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblCancel.setForeground(new java.awt.Color(24, 27, 59));
        lblCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/close-icon.png"))); // NOI18N
        lblCancel.setText("Cancel");
        lblCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelMouseClicked(evt);
            }
        });

        loginUsernameSep.setBackground(new java.awt.Color(24, 27, 59));

        loginPasswordSep.setBackground(new java.awt.Color(24, 27, 59));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/vesp.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginUsernameSep)
                    .addComponent(loginPasswordSep)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(lblCancel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsernameSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPasswordSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(lblCancel))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(24, 27, 59));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 255, 233));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/teacher (1).png"))); // NOI18N
        jLabel1.setText("Smart Lab Assistant Master");

        lblUsername.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(111, 255, 233));
        lblUsername.setText("Username");

        txtUsername.setBackground(new java.awt.Color(24, 27, 59));
        txtUsername.setFont(new java.awt.Font("Arima Madurai Black", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(111, 255, 233));
        lblPassword.setText("Password");

        txtPassword.setBackground(new java.awt.Color(24, 27, 59));
        txtPassword.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(111, 255, 233));
        txtPassword.setBorder(null);

        lblEmail.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(111, 255, 233));
        lblEmail.setText("e-Mail");

        txtEmail.setBackground(new java.awt.Color(24, 27, 59));
        txtEmail.setFont(new java.awt.Font("Arima Madurai Black", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblContactNo.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblContactNo.setForeground(new java.awt.Color(111, 255, 233));
        lblContactNo.setText("Contact No.");

        txtContactNo.setBackground(new java.awt.Color(24, 27, 59));
        txtContactNo.setFont(new java.awt.Font("Arima Madurai Black", 0, 18)); // NOI18N
        txtContactNo.setForeground(new java.awt.Color(255, 255, 255));
        txtContactNo.setBorder(null);

        usernameSep.setBackground(new java.awt.Color(111, 255, 233));

        passwordSep.setBackground(new java.awt.Color(111, 255, 233));

        emailSep.setBackground(new java.awt.Color(111, 255, 233));

        contactNoSep.setBackground(new java.awt.Color(111, 255, 233));

        lblSignup.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblSignup.setForeground(new java.awt.Color(255, 255, 255));
        lblSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/singup.png"))); // NOI18N
        lblSignup.setText("Sign Up");
        lblSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword)
                    .addComponent(txtEmail)
                    .addComponent(txtContactNo)
                    .addComponent(usernameSep)
                    .addComponent(passwordSep)
                    .addComponent(emailSep)
                    .addComponent(contactNoSep)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblEmail)
                            .addComponent(lblContactNo)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblContactNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNoSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblSignup)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1255, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginPasswordActionPerformed
        // TODO add your handling code here:
        processLogin();
    }//GEN-LAST:event_txtLoginPasswordActionPerformed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        processLogin();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to Exit?", "Login", JOptionPane.YES_NO_OPTION);
        if(ans == JOptionPane.YES_OPTION){
            close();
        }
    }//GEN-LAST:event_lblCancelMouseClicked

    private void lblSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignupMouseClicked
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO user(username, password, email, contactno)"
                    + "VALUES(?, ?, ?, ?)";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtUsername.getText());
            preparedStatement.setString(2, txtPassword.getText());
            preparedStatement.setString(3, txtEmail.getText());
            preparedStatement.setString(4, txtContactNo.getText());
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Signup Successful");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue"+e.getMessage());
        }
        finally{
            txtUsername.setText("");
            txtPassword.setText("");
            txtEmail.setText("");
            txtContactNo.setText("");
        }
    }//GEN-LAST:event_lblSignupMouseClicked

    private void txtLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsernameActionPerformed
        // TODO add your handling code here:
        processLogin();
    }//GEN-LAST:event_txtLoginUsernameActionPerformed

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoginMouseEntered
    private void close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    private void processLogin(){
        if(checkTextFields()){
        try{
            String sql = "SELECT * FROM user WHERE username=? and password=?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtLoginUsername.getText());
            preparedStatement.setString(2, txtLoginPassword.getText());
            rs = preparedStatement.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Login Successful","Login",JOptionPane.INFORMATION_MESSAGE);
                
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new SlamMainFrame().setVisible(true);
            }
        });
            }
            else{
            JOptionPane.showMessageDialog(null,"Login Unsuccessful","Login",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Something went Wrong","Login",JOptionPane.ERROR_MESSAGE);
        }
        }
        else{
            JOptionPane.showMessageDialog(null,"Some fields are missing! Better Luck Next Time!","Login",JOptionPane.ERROR_MESSAGE);
        }
    }
    private boolean checkTextFields(){
        if(txtLoginUsername.getText().equals("")||txtLoginPassword.getText().equals("")){
            return false;
        }
        else{
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlamLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlamLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlamLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlamLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlamLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator contactNoSep;
    private javax.swing.JSeparator emailSep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignup;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JSeparator loginPasswordSep;
    private javax.swing.JSeparator loginUsernameSep;
    private javax.swing.JSeparator passwordSep;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JSeparator usernameSep;
    // End of variables declaration//GEN-END:variables
}
