
import java.awt.Color;
import javax.swing.ImageIcon;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class SlamMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form SlamDashboard
     */
    public SlamMainFrame() {
        initComponents();
        btnStudent.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightBtnStudent.png"));
        btnMarks.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightBtnMarks.png"));
        btnAttendance.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightBtnAttendance.png"));
        btnReport.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\lightReport.png"));
        btnSubject.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\lightSubject.png"));
        btnDopDos.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\lightDate.png"));
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        StudentIconPanel = new javax.swing.JPanel();
        btnStudent = new javax.swing.JButton();
        lblStudent = new javax.swing.JLabel();
        AttendanceIconPanel = new javax.swing.JPanel();
        btnAttendance = new javax.swing.JButton();
        lblAttendance = new javax.swing.JLabel();
        MarksIconPanel = new javax.swing.JPanel();
        btnMarks = new javax.swing.JButton();
        lblMarks = new javax.swing.JLabel();
        ReportIconPanel = new javax.swing.JPanel();
        btnReport = new javax.swing.JButton();
        lblReport = new javax.swing.JLabel();
        DateIconPanel = new javax.swing.JPanel();
        btnDopDos = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        SubjectIconPanel = new javax.swing.JPanel();
        btnSubject = new javax.swing.JButton();
        lblSubject = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 15, 19));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        StudentIconPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnStudent.setBackground(new java.awt.Color(255, 255, 255));
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/blackStudent.png"))); // NOI18N
        btnStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 15, 19), 2, true));
        btnStudent.setPreferredSize(new java.awt.Dimension(70, 70));
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudentMouseExited(evt);
            }
        });
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        lblStudent.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudent.setText("Student");

        javax.swing.GroupLayout StudentIconPanelLayout = new javax.swing.GroupLayout(StudentIconPanel);
        StudentIconPanel.setLayout(StudentIconPanelLayout);
        StudentIconPanelLayout.setHorizontalGroup(
            StudentIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentIconPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(StudentIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentIconPanelLayout.setVerticalGroup(
            StudentIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStudent))
        );

        AttendanceIconPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnAttendance.setBackground(new java.awt.Color(255, 255, 255));
        btnAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/blackAttendance.png"))); // NOI18N
        btnAttendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 15, 19), 2, true));
        btnAttendance.setPreferredSize(new java.awt.Dimension(70, 70));
        btnAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAttendanceMouseExited(evt);
            }
        });
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });

        lblAttendance.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblAttendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttendance.setText("Attendance");

        javax.swing.GroupLayout AttendanceIconPanelLayout = new javax.swing.GroupLayout(AttendanceIconPanel);
        AttendanceIconPanel.setLayout(AttendanceIconPanelLayout);
        AttendanceIconPanelLayout.setHorizontalGroup(
            AttendanceIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendanceIconPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AttendanceIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttendanceIconPanelLayout.createSequentialGroup()
                        .addComponent(btnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttendanceIconPanelLayout.createSequentialGroup()
                        .addComponent(lblAttendance)
                        .addContainerGap())))
        );
        AttendanceIconPanelLayout.setVerticalGroup(
            AttendanceIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendanceIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAttendance))
        );

        MarksIconPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnMarks.setBackground(new java.awt.Color(255, 255, 255));
        btnMarks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/blackMarks.png"))); // NOI18N
        btnMarks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 15, 19), 2, true));
        btnMarks.setPreferredSize(new java.awt.Dimension(70, 70));
        btnMarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMarksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMarksMouseExited(evt);
            }
        });
        btnMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarksActionPerformed(evt);
            }
        });

        lblMarks.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblMarks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarks.setText("Marks");

        javax.swing.GroupLayout MarksIconPanelLayout = new javax.swing.GroupLayout(MarksIconPanel);
        MarksIconPanel.setLayout(MarksIconPanelLayout);
        MarksIconPanelLayout.setHorizontalGroup(
            MarksIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarksIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MarksIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MarksIconPanelLayout.setVerticalGroup(
            MarksIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarksIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMarks))
        );

        ReportIconPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnReport.setBackground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/blackReport.png"))); // NOI18N
        btnReport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 15, 19), 2, true));
        btnReport.setPreferredSize(new java.awt.Dimension(70, 70));
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        lblReport.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setText("Report");

        javax.swing.GroupLayout ReportIconPanelLayout = new javax.swing.GroupLayout(ReportIconPanel);
        ReportIconPanel.setLayout(ReportIconPanelLayout);
        ReportIconPanelLayout.setHorizontalGroup(
            ReportIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReportIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReportIconPanelLayout.setVerticalGroup(
            ReportIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReport))
        );

        DateIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        DateIconPanel.setPreferredSize(new java.awt.Dimension(102, 108));

        btnDopDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/blackDate.png"))); // NOI18N
        btnDopDos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnDopDos.setPreferredSize(new java.awt.Dimension(70, 70));
        btnDopDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDopDosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDopDosMouseExited(evt);
            }
        });
        btnDopDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDopDosActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblDate.setText("Date");

        javax.swing.GroupLayout DateIconPanelLayout = new javax.swing.GroupLayout(DateIconPanel);
        DateIconPanel.setLayout(DateIconPanelLayout);
        DateIconPanelLayout.setHorizontalGroup(
            DateIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DateIconPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btnDopDos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(DateIconPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DateIconPanelLayout.setVerticalGroup(
            DateIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DateIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDopDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblDate))
        );

        SubjectIconPanel.setBackground(new java.awt.Color(255, 255, 255));
        SubjectIconPanel.setPreferredSize(new java.awt.Dimension(102, 108));

        btnSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/blackSubject.png"))); // NOI18N
        btnSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSubject.setPreferredSize(new java.awt.Dimension(70, 70));
        btnSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubjectMouseExited(evt);
            }
        });
        btnSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectActionPerformed(evt);
            }
        });

        lblSubject.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblSubject.setText("Subject");

        javax.swing.GroupLayout SubjectIconPanelLayout = new javax.swing.GroupLayout(SubjectIconPanel);
        SubjectIconPanel.setLayout(SubjectIconPanelLayout);
        SubjectIconPanelLayout.setHorizontalGroup(
            SubjectIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addGroup(SubjectIconPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSubject)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SubjectIconPanelLayout.setVerticalGroup(
            SubjectIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectIconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubject))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(StudentIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubjectIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AttendanceIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MarksIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 738, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReportIconPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AttendanceIconPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentIconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MarksIconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateIconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(SubjectIconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(1400, 750));
        MainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1376, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        StudentPanel student = new StudentPanel();
        MainPanel.add(student);
        student.setVisible(true);
        MainPanel.revalidate();
        repaint();
        btnStudent.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightBtnStudent.png"));
        btnMarks.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackMarks.png"));
        btnAttendance.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackAttendance.png"));
        btnReport.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackReport.png"));
        btnSubject.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackSubject.png"));
        btnDopDos.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackDate.png"));
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        AttendancePanel attendance = new AttendancePanel();
        MainPanel.add(attendance);
        attendance.setVisible(true);
        MainPanel.revalidate();
        repaint();
        btnAttendance.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightBtnAttendance.png"));
        btnStudent.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackStudent.png"));
        btnMarks.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackMarks.png"));
        btnReport.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackReport.png"));
        btnSubject.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackSubject.png"));
        btnDopDos.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackDate.png"));
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarksActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MarksPanel marks = new MarksPanel();
        MainPanel.add(marks);
        marks.setVisible(true);
        MainPanel.revalidate();
        repaint();
        btnMarks.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\lightBtnMarks.png"));
        btnStudent.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackStudent.png"));
        btnAttendance.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackAttendance.png"));
        btnReport.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackReport.png"));
        btnSubject.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackSubject.png"));
        btnDopDos.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackDate.png"));
    }//GEN-LAST:event_btnMarksActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        ReportPanel report = new ReportPanel();
        MainPanel.add(report);
        report.setVisible(true);
        MainPanel.revalidate();
        repaint();
        btnMarks.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackMarks.png"));
        btnStudent.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackStudent.png"));
        btnAttendance.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackAttendance.png"));
        btnReport.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\lightReport.png"));
        btnSubject.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackSubject.png"));
        btnDopDos.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackDate.png"));
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseEntered
        // TODO add your handling code here:
        StudentIconPanel.setBackground(new Color(14,78,92));
        lblStudent.setForeground(new Color(27,154,170));
    }//GEN-LAST:event_btnStudentMouseEntered

    private void btnStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseExited
        // TODO add your handling code here:
        StudentIconPanel.setBackground(new Color(255,255,255));
        lblStudent.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnStudentMouseExited

    private void btnMarksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarksMouseEntered
        // TODO add your handling code here:
        MarksIconPanel.setBackground(new Color(81,29,31));
        lblMarks.setForeground(new Color(242,84,91));
    }//GEN-LAST:event_btnMarksMouseEntered

    private void btnMarksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarksMouseExited
        // TODO add your handling code here:
        MarksIconPanel.setBackground(new Color(255,255,255));
        lblMarks.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnMarksMouseExited

    private void btnAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttendanceMouseEntered
        // TODO add your handling code here:
        AttendanceIconPanel.setBackground(new Color(64,23,61));
        lblAttendance.setForeground(new Color(233,82,222));
    }//GEN-LAST:event_btnAttendanceMouseEntered

    private void btnAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttendanceMouseExited
        // TODO add your handling code here:
        AttendanceIconPanel.setBackground(new Color(255,255,255));
        lblAttendance.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnAttendanceMouseExited

    private void btnDopDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDopDosActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        DopDosGeneration DopDos = new DopDosGeneration();
        MainPanel.add(DopDos);
        DopDos.setVisible(true);
        MainPanel.revalidate();
        repaint();
        btnMarks.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackMarks.png"));
        btnStudent.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackStudent.png"));
        btnAttendance.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackAttendance.png"));
        btnReport.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackReport.png"));
        btnSubject.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackSubject.png"));
        btnDopDos.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\lightDate.png"));
    }//GEN-LAST:event_btnDopDosActionPerformed

    private void btnSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        SubjectPanel subject = new SubjectPanel();
        MainPanel.add(subject);
        subject.setVisible(true);
        MainPanel.revalidate();
        repaint();
        btnMarks.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackMarks.png"));
        btnStudent.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackStudent.png"));
        btnAttendance.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackAttendance.png"));
        btnReport.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\blackReport.png"));
        btnSubject.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\lightSubject.png"));
        btnDopDos.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\blackDate.png"));
    }//GEN-LAST:event_btnSubjectActionPerformed

    private void btnSubjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectMouseEntered
        // TODO add your handling code here:
        SubjectIconPanel.setBackground(new Color(24,27,59));
        lblSubject.setForeground(new Color(87,98,213));
    }//GEN-LAST:event_btnSubjectMouseEntered

    private void btnSubjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectMouseExited
        // TODO add your handling code here:
        SubjectIconPanel.setBackground(new Color(255,255,255));
        lblSubject.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnSubjectMouseExited

    private void btnDopDosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDopDosMouseEntered
        // TODO add your handling code here:
        DateIconPanel.setBackground(new Color(28,40,15));
        lblDate.setForeground(new Color(110,160,58));
    }//GEN-LAST:event_btnDopDosMouseEntered

    private void btnDopDosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDopDosMouseExited
        // TODO add your handling code here:
        DateIconPanel.setBackground(new Color(255,255,255));
        lblDate.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnDopDosMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        // TODO add your handling code here:
        ReportIconPanel.setBackground(new Color(163,0,0));
        lblReport.setForeground(new Color(218,80,0));
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        // TODO add your handling code here:
        ReportIconPanel.setBackground(new Color(255,255,255));
        lblReport.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnReportMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlamMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlamMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlamMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlamMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlamMainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AttendanceIconPanel;
    private javax.swing.JPanel DateIconPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MarksIconPanel;
    private javax.swing.JPanel ReportIconPanel;
    private javax.swing.JPanel StudentIconPanel;
    private javax.swing.JPanel SubjectIconPanel;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnDopDos;
    private javax.swing.JButton btnMarks;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnSubject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAttendance;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMarks;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblSubject;
    // End of variables declaration//GEN-END:variables
}
