
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.coobird.thumbnailator.Thumbnails;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class StudentPanel extends javax.swing.JPanel {
    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet rs = null;
    /**
     * Creates new form StudentPanel
     */
    static{
        sql = "SELECT * FROM student ORDER BY name ASC";
    }
    public StudentPanel() {
        initComponents();
        conn = SlamSqlConnect.connectDb();
        updatejStudentTableData(StudentPanel.sql);
        lblStudentId.setVisible(false);
        txtStudentId.setVisible(false);
        btnUpdate.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkUpdate.png"));
        btnDelete.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkDelete.png"));
        btnClear.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkClear.png"));
        btnSave.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkSave.png"));
        txtSearch.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchFilter();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                searchFilter();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {}
        });
    }

    private void searchFilter(){
        String key = txtSearch.getText();
        String sql = "SELECT * FROM student WHERE name LIKE '%"+key+"%'";
        updatejStudentTableData(sql);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        searchSep = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblEnrollmentno = new javax.swing.JLabel();
        lblRollno = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        lblBatch = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEnrollmentNo = new javax.swing.JTextField();
        txtRollNo = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        txtBatch = new javax.swing.JTextField();
        btnUploadImage = new javax.swing.JButton();
        nameSep = new javax.swing.JSeparator();
        enrollmentnoSep = new javax.swing.JSeparator();
        rollnoSep = new javax.swing.JSeparator();
        branchSep = new javax.swing.JSeparator();
        semesterSep = new javax.swing.JSeparator();
        batchSep = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jStudentTableData = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblImage = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1400, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 750));

        jPanel3.setBackground(new java.awt.Color(14, 78, 92));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/lightUpdate.png"))); // NOI18N
        btnUpdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnUpdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnUpdateFocusLost(evt);
            }
        });
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/lightDelete.png"))); // NOI18N
        btnDelete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnDeleteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnDeleteFocusLost(evt);
            }
        });
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/lightClear.png"))); // NOI18N
        btnClear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnClearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnClearFocusLost(evt);
            }
        });
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/lightSave.png"))); // NOI18N
        btnSave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSaveFocusLost(evt);
            }
        });
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Arima Madurai Black", 0, 20)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(27, 154, 170));
        lblSearch.setText("Search");

        txtSearch.setBackground(new java.awt.Color(14, 78, 92));
        txtSearch.setFont(new java.awt.Font("Arima Madurai Black", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        searchSep.setBackground(new java.awt.Color(27, 154, 170));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(741, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchSep, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(1372, 617));

        lblName.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblName.setForeground(new java.awt.Color(27, 154, 170));
        lblName.setText("Name");

        lblEnrollmentno.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblEnrollmentno.setForeground(new java.awt.Color(27, 154, 170));
        lblEnrollmentno.setText("Enrollment No.");

        lblRollno.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblRollno.setForeground(new java.awt.Color(27, 154, 170));
        lblRollno.setText("Roll No.");

        lblBranch.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblBranch.setForeground(new java.awt.Color(27, 154, 170));
        lblBranch.setText("Branch");

        lblSemester.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(27, 154, 170));
        lblSemester.setText("Semester");

        lblBatch.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblBatch.setForeground(new java.awt.Color(27, 154, 170));
        lblBatch.setText("Batch");

        txtName.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNameMouseExited(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtEnrollmentNo.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtEnrollmentNo.setBorder(null);
        txtEnrollmentNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEnrollmentNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnrollmentNoFocusLost(evt);
            }
        });
        txtEnrollmentNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEnrollmentNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEnrollmentNoMouseExited(evt);
            }
        });
        txtEnrollmentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnrollmentNoActionPerformed(evt);
            }
        });

        txtRollNo.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtRollNo.setBorder(null);
        txtRollNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRollNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRollNoFocusLost(evt);
            }
        });
        txtRollNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtRollNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRollNoMouseExited(evt);
            }
        });

        txtBranch.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtBranch.setBorder(null);
        txtBranch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBranchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBranchFocusLost(evt);
            }
        });
        txtBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBranchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBranchMouseExited(evt);
            }
        });

        txtSemester.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtSemester.setBorder(null);
        txtSemester.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSemesterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSemesterFocusLost(evt);
            }
        });
        txtSemester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSemesterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSemesterMouseExited(evt);
            }
        });

        txtBatch.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtBatch.setBorder(null);
        txtBatch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBatchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBatchFocusLost(evt);
            }
        });
        txtBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBatchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBatchMouseExited(evt);
            }
        });
        txtBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchActionPerformed(evt);
            }
        });

        btnUploadImage.setBackground(new java.awt.Color(255, 255, 255));
        btnUploadImage.setFont(new java.awt.Font("Arima Madurai Black", 1, 18)); // NOI18N
        btnUploadImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlamImages/image upload.png"))); // NOI18N
        btnUploadImage.setText("Upload Image");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        nameSep.setBackground(new java.awt.Color(0, 153, 204));

        enrollmentnoSep.setBackground(new java.awt.Color(0, 153, 204));

        rollnoSep.setBackground(new java.awt.Color(0, 153, 204));

        branchSep.setBackground(new java.awt.Color(0, 153, 204));

        semesterSep.setBackground(new java.awt.Color(0, 153, 204));

        batchSep.setBackground(new java.awt.Color(0, 153, 204));

        jStudentTableData.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jStudentTableData.setForeground(new java.awt.Color(14, 78, 92));
        jStudentTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jStudentTableData.setRowHeight(25);
        jStudentTableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStudentTableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jStudentTableData);

        jDesktopPane1.setBackground(new java.awt.Color(14, 78, 92));

        jDesktopPane1.setLayer(lblImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblStudentId.setText("StudentId");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUploadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStudentId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStudentId))
                        .addGap(18, 18, 18)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(semesterSep, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(batchSep, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameSep, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enrollmentnoSep, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBatch)
                            .addComponent(txtBranch)
                            .addComponent(lblBatch, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rollnoSep, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(branchSep, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRollno, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEnrollmentNo)
                            .addComponent(lblEnrollmentno, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(lblBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(lblEnrollmentno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnrollmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrollmentnoSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRollno)
                            .addComponent(lblBranch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rollnoSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(branchSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBatch)
                            .addComponent(lblSemester))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(semesterSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(batchSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStudentId)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addComponent(jDesktopPane1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatejStudentTableData(String sql){
        //String sql = "SELECT * FROM student ORDER BY name ASC";
        try{
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jStudentTableData.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
        finally{
            try{
            rs.close();
            preparedStatement.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());    
            }
        }
    }    
    private void clear(){
        txtStudentId.setText("");
        txtName.setText("");
        txtEnrollmentNo.setText("");
        txtRollNo.setText("");
        txtBranch.setText("");
        txtSemester.setText("");
        txtBatch.setText("");
        lblImage.setIcon(null);
    }
    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        nameSep.setBackground(new Color(14,78,92));
        lblName.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        nameSep.setBackground(new Color(0,153,204));
        lblName.setForeground(new Color(0,153,204));
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseEntered
        // TODO add your handling code here:
        nameSep.setBackground(new Color(14,78,92));
        lblName.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtNameMouseEntered

    private void txtNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseExited
        // TODO add your handling code here:
        if(!txtName.hasFocus()){
            nameSep.setBackground(new Color(0,153,204));
            lblName.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_txtNameMouseExited

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEnrollmentNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnrollmentNoFocusGained
        // TODO add your handling code here:
        enrollmentnoSep.setBackground(new Color(14,78,92));
        lblEnrollmentno.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtEnrollmentNoFocusGained

    private void txtEnrollmentNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnrollmentNoFocusLost
        // TODO add your handling code here:
        enrollmentnoSep.setBackground(new Color(0,153,204));
        lblEnrollmentno.setForeground(new Color(0,153,204));
    }//GEN-LAST:event_txtEnrollmentNoFocusLost

    private void txtEnrollmentNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEnrollmentNoMouseEntered
        // TODO add your handling code here:
        enrollmentnoSep.setBackground(new Color(14,78,92));
        lblEnrollmentno.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtEnrollmentNoMouseEntered

    private void txtEnrollmentNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEnrollmentNoMouseExited
        // TODO add your handling code here:
        if(!txtEnrollmentNo.hasFocus()){
        enrollmentnoSep.setBackground(new Color(0,153,204));
        lblEnrollmentno.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_txtEnrollmentNoMouseExited

    private void txtEnrollmentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnrollmentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnrollmentNoActionPerformed

    private void txtRollNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRollNoFocusGained
        // TODO add your handling code here:
        rollnoSep.setBackground(new Color(14,78,92));
        lblRollno.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtRollNoFocusGained

    private void txtRollNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRollNoFocusLost
        // TODO add your handling code here:
        rollnoSep.setBackground(new Color(0,153,204));
        lblRollno.setForeground(new Color(0,153,204));
    }//GEN-LAST:event_txtRollNoFocusLost

    private void txtRollNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRollNoMouseEntered
        // TODO add your handling code here:
        rollnoSep.setBackground(new Color(14,78,92));
        lblRollno.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtRollNoMouseEntered

    private void txtRollNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRollNoMouseExited
        // TODO add your handling code here:
        if(!txtRollNo.hasFocus()){
        rollnoSep.setBackground(new Color(0,153,204));
        lblRollno.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_txtRollNoMouseExited

    private void txtBranchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBranchFocusGained
        // TODO add your handling code here:
        branchSep.setBackground(new Color(14,78,92));
        lblBranch.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtBranchFocusGained

    private void txtBranchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBranchFocusLost
        // TODO add your handling code here:
        branchSep.setBackground(new Color(0,153,204));
        lblBranch.setForeground(new Color(0,153,204));
    }//GEN-LAST:event_txtBranchFocusLost

    private void txtBranchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBranchMouseEntered
        // TODO add your handling code here:
        branchSep.setBackground(new Color(14,78,92));
        lblBranch.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtBranchMouseEntered

    private void txtBranchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBranchMouseExited
        // TODO add your handling code here:
        if(!txtBranch.hasFocus()){
        branchSep.setBackground(new Color(0,153,204));
        lblBranch.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_txtBranchMouseExited

    private void txtSemesterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemesterFocusGained
        // TODO add your handling code here:
        semesterSep.setBackground(new Color(14,78,92));
        lblSemester.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtSemesterFocusGained

    private void txtSemesterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemesterFocusLost
        // TODO add your handling code here:
        semesterSep.setBackground(new Color(0,153,204));
        lblSemester.setForeground(new Color(0,153,204));
    }//GEN-LAST:event_txtSemesterFocusLost

    private void txtSemesterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSemesterMouseEntered
        // TODO add your handling code here:
        semesterSep.setBackground(new Color(14,78,92));
        lblSemester.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtSemesterMouseEntered

    private void txtSemesterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSemesterMouseExited
        // TODO add your handling code here:
        if(!txtSemester.hasFocus()){
        semesterSep.setBackground(new Color(0,153,204));
        lblSemester.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_txtSemesterMouseExited

    private void txtBatchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBatchFocusGained
        // TODO add your handling code here:
        batchSep.setBackground(new Color(14,78,92));
        lblBatch.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtBatchFocusGained

    private void txtBatchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBatchFocusLost
        // TODO add your handling code here:
        batchSep.setBackground(new Color(0,153,204));
        lblBatch.setForeground(new Color(0,153,204));
    }//GEN-LAST:event_txtBatchFocusLost

    private void txtBatchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBatchMouseEntered
        // TODO add your handling code here:
        batchSep.setBackground(new Color(14,78,92));
        lblBatch.setForeground(new Color(14,78,92));
    }//GEN-LAST:event_txtBatchMouseEntered

    private void txtBatchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBatchMouseExited
        // TODO add your handling code here:
        if(!txtBatch.hasFocus()){
        batchSep.setBackground(new Color(0,153,204));
        lblBatch.setForeground(new Color(0,153,204));
        }
    }//GEN-LAST:event_txtBatchMouseExited

    private void txtBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatchActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File sourceFile = fileChooser.getSelectedFile();
        if(sourceFile!=null){
            imagePath = sourceFile.getAbsolutePath();
            //txtImagePath.setText(imagePath);
            try{
                File image = new File(imagePath);
                BufferedImage thumbnail = Thumbnails.of(image).size(180,220).asBufferedImage();

                /******************************************************************************
                * ****************************************************************************
                * The Below Code is used to convert the image which is converted to thumbnail
                * to byte array so that we can store the byte array in our database as blob
                * data type
                * ****************************************************************************
                * ****************************************************************************
                */
                ByteArrayOutputStream os = new ByteArrayOutputStream();
                ImageIO.write(thumbnail,"jpg", os);
                byteImage = os.toByteArray();
                /******************************************************************************
                * ****************************************************************************
                */

                viewImage = new ImageIcon(thumbnail);
                lblImage.setIcon(viewImage);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void jStudentTableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStudentTableDataMouseClicked
        // TODO add your handling code here:
        int selectedRow = jStudentTableData.getSelectedRow();
        String selectedSId = jStudentTableData.getModel().getValueAt(selectedRow, 0).toString();
        try{
            String sql = "SELECT * FROM student WHERE sid = " + selectedSId;
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            if(rs.next()){
                txtStudentId.setText(rs.getString("sid"));
                txtName.setText(rs.getString("name"));
                txtEnrollmentNo.setText(rs.getString("enrollmentno"));
                txtRollNo.setText(rs.getString("rollno"));
                txtSemester.setText(rs.getString("semester"));
                txtBranch.setText(rs.getString("branch"));
                txtBatch.setText(rs.getString("batch"));
                byte [] selectedImage = rs.getBytes("studimage");
                byteImage = selectedImage;
                BufferedImage img = Thumbnails.of(ImageIO.read(new ByteArrayInputStream(selectedImage))).size(180,220).asBufferedImage();
                ImageIcon i = new ImageIcon(img);
                lblImage.setIcon(i);
            }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jStudentTableDataMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if("".equals(txtStudentId.getText())){
            JOptionPane.showMessageDialog(null,"Please select record to delete");
        }
        else{
            int btn = JOptionPane.showConfirmDialog(null,"Are you sure you wanna delete the record?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(btn == JOptionPane.YES_OPTION){
                try{
                    String sql = "DELETE FROM student WHERE sid = ?";
                    preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setInt(1, Integer.parseInt(txtStudentId.getText()));
                    preparedStatement.execute();
                    JOptionPane.showMessageDialog(null,"Record Deleted Successfully!");
                    updatejStudentTableData(StudentPanel.sql);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
                }
                finally{
                    try{
                        preparedStatement.close();
                    }
                    catch(Exception e){}
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE student SET name = ?,enrollmentno = ?, rollno = ?, semester = ?,"
            + "branch = ?, batch = ?, studimage = ? WHERE sid = ?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtName.getText());
            preparedStatement.setString(2, txtEnrollmentNo.getText());
            preparedStatement.setString(3, txtRollNo.getText());
            preparedStatement.setString(4, txtSemester.getText());
            preparedStatement.setString(5, txtBranch.getText());
            preparedStatement.setString(6, txtBatch.getText());
            preparedStatement.setBytes(7, byteImage);
            preparedStatement.setInt(8, Integer.parseInt(txtStudentId.getText()));
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Record Updated Successfully");
            updatejStudentTableData(StudentPanel.sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnUpdateFocusGained
        // TODO add your handling code here:
        btnUpdate.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkUpdate.png"));
    }//GEN-LAST:event_btnUpdateFocusGained

    private void btnUpdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnUpdateFocusLost
        // TODO add your handling code here:
        btnUpdate.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightUpdate.png"));
    }//GEN-LAST:event_btnUpdateFocusLost

    private void btnDeleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDeleteFocusGained
        // TODO add your handling code here:
        btnDelete.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkDelete.png"));
    }//GEN-LAST:event_btnDeleteFocusGained

    private void btnDeleteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnDeleteFocusLost
        // TODO add your handling code here:
        btnDelete.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightDelete.png"));
    }//GEN-LAST:event_btnDeleteFocusLost

    private void btnClearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClearFocusGained
        // TODO add your handling code here:
        btnClear.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkClear.png"));
    }//GEN-LAST:event_btnClearFocusGained

    private void btnClearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClearFocusLost
        // TODO add your handling code here:
        btnClear.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightClear.png"));
    }//GEN-LAST:event_btnClearFocusLost

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:        
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO student(name, enrollmentno, rollno, semester, branch, batch, studimage)"
            + "VALUES(?, ?, ?, ?, ?, ?, ?)";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtName.getText());
            preparedStatement.setString(2, txtEnrollmentNo.getText());
            preparedStatement.setString(3, txtRollNo.getText());
            preparedStatement.setString(4, txtSemester.getText());
            preparedStatement.setString(5, txtBranch.getText());
            preparedStatement.setString(6, txtBatch.getText());
            preparedStatement.setBytes(7, byteImage);
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Record Inserted Successfully");
            updatejStudentTableData(StudentPanel.sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseExited

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusGained
        // TODO add your handling code here:
        btnSave.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\darkSave.png"));
    }//GEN-LAST:event_btnSaveFocusGained

    private void btnSaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusLost
        // TODO add your handling code here:
        btnSave.setIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\SlamImages\\lightSave.png"));
    }//GEN-LAST:event_btnSaveFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator batchSep;
    private javax.swing.JSeparator branchSep;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JSeparator enrollmentnoSep;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jStudentTableData;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblEnrollmentno;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRollno;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JSeparator nameSep;
    private javax.swing.JSeparator rollnoSep;
    private javax.swing.JSeparator searchSep;
    private javax.swing.JSeparator semesterSep;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtEnrollmentNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRollNo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
    private String imagePath = null;
    private ImageIcon viewImage = null;
    private byte[] byteImage = null;
    static final String sql; 
}
