
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class SubjectPanel extends javax.swing.JPanel {
    static Connection conn = null;
    static PreparedStatement preparedStatement = null;
    static ResultSet rs = null;
    /**
     * Creates new form SubjectPanel
     */
    public SubjectPanel() {
        initComponents();
        conn = SlamSqlConnect.connectDb();
        lblSubId.setVisible(false);
        txtSubId.setVisible(false);
        updatejSubjectTableData();
        btnUpdate.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\darkUpdateS.png"));
        btnDelete.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\darkDeleteS.png"));
        btnClear.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\darkClearS.png"));
        btnSave.setRolloverIcon(new ImageIcon("C:\\Users\\KriShaivi\\Desktop\\Advance Java\\SlamProject\\src\\Copy\\darkSaveS.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lblSubjectName = new javax.swing.JLabel();
        txtSubjectName = new javax.swing.JTextField();
        lblSemester = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();
        lblBranch = new javax.swing.JLabel();
        txtBranch = new javax.swing.JTextField();
        lblBatch = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSubjectTableData = new javax.swing.JTable();
        lblSubId = new javax.swing.JLabel();
        txtSubId = new javax.swing.JTextField();
        subjectNameSep = new javax.swing.JSeparator();
        semesterSep = new javax.swing.JSeparator();
        branchSep = new javax.swing.JSeparator();
        batchSep = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSubjectDatesTableData = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(24, 27, 59));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 105));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/lightSubjectS.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/lightUpdateS.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/lightDeleteS.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Copy/lightClearS.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arima Madurai Black", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(87, 98, 213));
        jLabel1.setText("Search");

        jTextField1.setBackground(new java.awt.Color(24, 27, 59));
        jTextField1.setFont(new java.awt.Font("Arima Madurai Black", 0, 18)); // NOI18N
        jTextField1.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(87, 98, 213));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblSubjectName.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblSubjectName.setForeground(new java.awt.Color(87, 98, 213));
        lblSubjectName.setText("Subject Name");

        txtSubjectName.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtSubjectName.setBorder(null);
        txtSubjectName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubjectNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubjectNameFocusLost(evt);
            }
        });
        txtSubjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectNameActionPerformed(evt);
            }
        });

        lblSemester.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(87, 98, 213));
        lblSemester.setText("Semester");

        txtSemester.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtSemester.setBorder(null);
        txtSemester.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSemesterFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSemesterFocusLost(evt);
            }
        });

        lblBranch.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblBranch.setForeground(new java.awt.Color(87, 98, 213));
        lblBranch.setText("Branch");

        txtBranch.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtBranch.setBorder(null);
        txtBranch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBranchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBranchFocusLost(evt);
            }
        });
        txtBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchActionPerformed(evt);
            }
        });

        lblBatch.setFont(new java.awt.Font("Arima Madurai Black", 1, 30)); // NOI18N
        lblBatch.setForeground(new java.awt.Color(87, 98, 213));
        lblBatch.setText("Batch");

        txtBatch.setFont(new java.awt.Font("Arima Madurai Black", 0, 24)); // NOI18N
        txtBatch.setBorder(null);
        txtBatch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBatchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBatchFocusLost(evt);
            }
        });
        txtBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatchActionPerformed(evt);
            }
        });

        jSubjectTableData.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jSubjectTableData.setForeground(new java.awt.Color(24, 27, 59));
        jSubjectTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSubjectTableData.setRowHeight(25);
        jSubjectTableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSubjectTableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jSubjectTableData);

        lblSubId.setText("SubId");

        subjectNameSep.setBackground(new java.awt.Color(87, 98, 213));

        semesterSep.setBackground(new java.awt.Color(87, 98, 213));
        semesterSep.setPreferredSize(new java.awt.Dimension(50, 10));

        branchSep.setBackground(new java.awt.Color(87, 98, 213));
        branchSep.setPreferredSize(new java.awt.Dimension(50, 10));

        batchSep.setBackground(new java.awt.Color(87, 98, 213));

        jSubjectDatesTableData.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jSubjectDatesTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSubjectDatesTableData.setRowHeight(20);
        jScrollPane2.setViewportView(jSubjectDatesTableData);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSubjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(txtSubjectName)
                    .addComponent(lblSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSemester)
                    .addComponent(lblBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBranch)
                    .addComponent(lblBatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBatch)
                    .addComponent(txtSubId)
                    .addComponent(lblSubId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subjectNameSep)
                    .addComponent(semesterSep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(branchSep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(batchSep))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(subjectNameSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(semesterSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(branchSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batchSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1376, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO subject(subjectname, semester,branch,batch) VALUES(?,?,?,?)";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtSubjectName.getText());
            preparedStatement.setInt(2, Integer.parseInt(txtSemester.getText()));
            preparedStatement.setString(3, txtBranch.getText());
            preparedStatement.setString(4, txtBatch.getText());
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Record Inserted Successfully");
            updatejSubjectTableData();
        }
        catch(Exception e){}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jSubjectTableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSubjectTableDataMouseClicked
        // TODO add your handling code here:
        int selectedRow = jSubjectTableData.getSelectedRow();
        String selectedSubId = jSubjectTableData.getModel().getValueAt(selectedRow, 0).toString();
        try{
            String sql = "SELECT * FROM subject WHERE subid = " + selectedSubId;
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            if(rs.next()){
                txtSubId.setText(rs.getString("subid"));
                txtSubjectName.setText(rs.getString("subjectname"));
                txtSemester.setText(rs.getString("semester"));
                txtBranch.setText(rs.getString("branch"));
                txtBatch.setText(rs.getString("batch"));
            }
            updatejSubjectDatesTableData();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jSubjectTableDataMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE subject SET subjectname=?,semester=?,branch=?,batch=? WHERE subid=?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtSubjectName.getText());
            preparedStatement.setInt(2, Integer.parseInt(txtSemester.getText()));
            preparedStatement.setString(3, txtBranch.getText());
            preparedStatement.setString(4, txtBatch.getText());
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Record Updated Successfully");
        }
        catch(Exception e){            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void clear(){
        txtSubId.setText("");
        txtSubjectName.setText("");
        txtSemester.setText("");
        txtBranch.setText("");
        txtBatch.setText("");
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if("".equals(txtSubId.getText())){
            JOptionPane.showMessageDialog(null,"Please select record to delete");
        }
        else{
            int btn = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(btn == JOptionPane.YES_OPTION){
                try{
                    String sql = "DELETE FROM subject WHERE subid = ?";
                    preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setInt(1, Integer.parseInt(txtSubId.getText()));
                    preparedStatement.execute();
                    JOptionPane.showMessageDialog(null,"Record Deleted Successfully!");
                    clear();
                    updatejSubjectTableData();
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
                }
                finally{
                    try{
                        preparedStatement.close();
                    }
                    catch(Exception e){}
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private void txtSubjectNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubjectNameFocusGained
        // TODO add your handling code here:
        lblSubjectName.setForeground(new Color(24,27,59));
        subjectNameSep.setBackground(new Color(24,27,59));
    }//GEN-LAST:event_txtSubjectNameFocusGained

    private void txtSubjectNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubjectNameFocusLost
        // TODO add your handling code here:
        lblSubjectName.setForeground(new Color(87,98,213));
        subjectNameSep.setBackground(new Color(87,98,213));
    }//GEN-LAST:event_txtSubjectNameFocusLost

    private void txtSemesterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemesterFocusGained
        // TODO add your handling code here:
        lblSemester.setForeground(new Color(24,27,59));
        semesterSep.setBackground(new Color(24,27,59));
    }//GEN-LAST:event_txtSemesterFocusGained

    private void txtSemesterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSemesterFocusLost
        // TODO add your handling code here:
        lblSemester.setForeground(new Color(87,98,213));
        semesterSep.setBackground(new Color(87,98,213));
    }//GEN-LAST:event_txtSemesterFocusLost

    private void txtBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchActionPerformed

    private void txtBranchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBranchFocusGained
        // TODO add your handling code here:
        lblBranch.setForeground(new Color(24,27,59));
        branchSep.setBackground(new Color(24,27,59));
    }//GEN-LAST:event_txtBranchFocusGained

    private void txtBranchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBranchFocusLost
        // TODO add your handling code here:
        lblBranch.setForeground(new Color(87,98,213));
        branchSep.setBackground(new Color(87,98,213));
    }//GEN-LAST:event_txtBranchFocusLost

    private void txtBatchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBatchFocusGained
        // TODO add your handling code here:
        lblBatch.setForeground(new Color(24,27,59));
        batchSep.setBackground(new Color(24,27,59));
    }//GEN-LAST:event_txtBatchFocusGained

    private void txtBatchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBatchFocusLost
        // TODO add your handling code here:
        lblBatch.setForeground(new Color(87,98,213));
        batchSep.setBackground(new Color(87,98,213));
    }//GEN-LAST:event_txtBatchFocusLost

    private void txtSubjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectNameActionPerformed
    
    private void updatejSubjectDatesTableData(){
        try{
            String sql = "SELECT experimentno, DOP, DOS FROM experiment WHERE subid ="+txtSubId.getText();
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jSubjectDatesTableData.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
        finally{
            try{
            rs.close();
            preparedStatement.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());    
            }
        }
    }
    
    
    
    private void updatejSubjectTableData(){
        try{
            String sql = "SELECT * FROM subject";
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jSubjectTableData.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
        finally{
            try{
            rs.close();
            preparedStatement.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());    
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator batchSep;
    private javax.swing.JSeparator branchSep;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jSubjectDatesTableData;
    private javax.swing.JTable jSubjectTableData;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSubId;
    private javax.swing.JLabel lblSubjectName;
    private javax.swing.JSeparator semesterSep;
    private javax.swing.JSeparator subjectNameSep;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtSubId;
    private javax.swing.JTextField txtSubjectName;
    // End of variables declaration//GEN-END:variables
}
